version: '4.0'

services:
  postgres:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - "D:/Java Projects/Patient-management/patient-service/db_volumes/patient-service-db:/var/lib/postgresql/data"
    networks:
      - internal

  patient-service:
    build:
      context: .
      dockerfile: DockerFile
    container_name: patient-service-app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge






# D:\Java Projects\Patient-management\patient-service\db_volumes\patient-service-db
# /var/lib/postgresql/data
