version: '4.0'

services:
  billing-service:
    build:
      context: .
      dockerfile: DockerFile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge






# D:\Java Projects\Patient-management\patient-service\db_volumes\patient-service-db
# /var/lib/postgresql/data
